name: Ubuntu rvv VLEN=1024 (clang 20)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: |
        sudo apt-get update -q -y
        sudo apt-get install -y cmake make g++-riscv64-linux-gnu qemu-user-static clang-20
    - name: Build
      run: |
        CXX=clang++-20 \
        CC=clang-20 \
        CXXFLAGS="--target=riscv64-linux-gnu -march=rv64gcv_zvbb" \
        cmake --toolchain=cmake/toolchains-ci/riscv64-linux-gnu.cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -B build \
        -DSIMDUTF_FAST_TESTS=On
        cmake --build build/ -j$(nproc)
    - name: Test VLEN=1024
      run: |
        export QEMU_LD_PREFIX="/usr/riscv64-linux-gnu"
        export QEMU_CPU="rv64,v=on,zvbb=on,vlen=1024,rvv_ta_all_1s=on,rvv_ma_all_1s=on"
        ctest --timeout 1800 --output-on-failure --test-dir build -j $(nproc)
