name: VS16-CI

on: [push, pull_request]

jobs:
  ci:
    name: windows-vs16
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        include:
          - {gen: Visual Studio 16 2019, arch: x64, shared: ON}
          - {gen: Visual Studio 16 2019, arch: x64, shared: OFF}
          - {gen: Visual Studio 16 2019, arch: Win32, shared: ON}
          - {gen: Visual Studio 16 2019, arch: Win32, shared: OFF}
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Configure
      run: |
        cmake -G "${{matrix.gen}}" -DSIMDUTF_BENCHMARKS=ON -A ${{matrix.arch}} -DBUILD_SHARED_LIBS=${{matrix.shared}} -B build
    - name: Build Debug
      run: cmake --build build --config Debug --verbose
    - name: Build Release
      run: cmake --build build --config Release --verbose
    - name: Run Release tests
      run: |
        cd build
        ctest -C Release   --output-on-failure
    - name: Run Debug tests
      run: |
        cd build
        ctest -C Debug  --output-on-failure
    - name: Install
      run: |
        cmake --install build --config Release
    - name: Test Installation
      run: |
        cmake -G "${{matrix.gen}}" -A ${{matrix.arch}}  -B build_install_test tests/installation_tests/find
        cmake --build build_install_test --config Release
